### ISSUE TITLE
Missing py.typed marker

### ISSUE THREAD

**Issue by phoenixr-codes** [JoelLefkowitz/convert-case#1]
# Bug Report

## Description

 A clear and concise description of the problem...

Importing this modules results in mypy `Skipping analyzing "convert_case": module is installed, but missing library stubs or py.typed marker`. White the library is typed, it is missing a py.typed file in the `src` directory.

## Is this a regression?

No

## Minimal Reproduction

```code
# FILE: main.py
import convert_case
```

```console
mypy main.py
```

## Stack trace / Error message

```text
error: Skipping analyzing "convert_case": module is installed, but missing library stubs or py.typed marker
```

## Your Environment

```text
CPython 3.10.6
mypy 1.0.1
```

**Comment by JoelLefkowitz** [comment]
Fixed in 24a92f27dcce07da8bc4bb80585dc64a4bb7bab0
